import React from 'react';

export default function GovernmentPortals() {
  return (
    <>
      <section id="portals" className="pad-s"><div className="wrap">
  <div className="shead reveal"><div className="st"><div className="sicon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="12" cy="12" r="9" /><path d="M3 12h18M12 3c2.5 2.5 4 6 4 9s-1.5 6.5-4 9c-2.5-2.5-4-6-4-9s1.5-6.5 4-9z" /></svg></div><div><h2>Government portals</h2><div className="sdesc">Verified official links to the registries and portals you actually use</div></div></div></div>
  <div className="portals">
    <a href="https://www.mca.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" data-item data-title="MCA Ministry of Corporate Affairs portal" data-cat="Government Portal" data-tags="mca roc incorporation filing portal"><div className="plogo">MCA</div><div><div className="pn">MCA V3</div><div className="pd">Incorporation, ROC filings, DIN</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://www.gst.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" style={{ "--d": "50ms" } as React.CSSProperties} data-item data-title="GST portal" data-cat="Government Portal" data-tags="gst returns registration portal tax"><div className="plogo">GST</div><div><div className="pn">GST Portal</div><div className="pd">Registration, returns, e-invoicing</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://www.startupindia.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" style={{ "--d": "100ms" } as React.CSSProperties} data-item data-title="Startup India portal DPIIT" data-cat="Government Portal" data-tags="startup india dpiit recognition portal"><div className="plogo">SI</div><div><div className="pn">Startup India</div><div className="pd">DPIIT recognition, benefits</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://www.incometax.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" style={{ "--d": "150ms" } as React.CSSProperties} data-item data-title="Income Tax e-filing portal" data-cat="Government Portal" data-tags="income tax itr tds portal efiling"><div className="plogo">IT</div><div><div className="pn">Income Tax</div><div className="pd">ITR filing, TDS, PAN, AIS</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://ipindia.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" style={{ "--d": "200ms" } as React.CSSProperties} data-item data-title="IP India Trademark Patent registry" data-cat="Government Portal" data-tags="trademark patent ip registry portal"><div className="plogo">IP</div><div><div className="pn">IP India</div><div className="pd">Trademark &amp; patent registry</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://www.rbi.org.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" data-item data-title="RBI Reserve Bank of India" data-cat="Government Portal" data-tags="rbi fema fdi banking portal"><div className="plogo">RBI</div><div><div className="pn">RBI</div><div className="pd">FEMA, FDI reporting, circulars</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://www.sebi.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" style={{ "--d": "50ms" } as React.CSSProperties} data-item data-title="SEBI Securities Exchange Board" data-cat="Government Portal" data-tags="sebi securities aif investors portal"><div className="plogo">SEBI</div><div><div className="pn">SEBI</div><div className="pd">Securities, AIFs, disclosures</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://udyamregistration.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" style={{ "--d": "100ms" } as React.CSSProperties} data-item data-title="Udyam MSME registration" data-cat="Government Portal" data-tags="udyam msme registration portal"><div className="plogo">MSME</div><div><div className="pn">Udyam</div><div className="pd">MSME / Udyam registration</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://www.dgft.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" style={{ "--d": "150ms" } as React.CSSProperties} data-item data-title="DGFT Import Export Code IEC" data-cat="Government Portal" data-tags="dgft iec import export portal"><div className="plogo">DGFT</div><div><div className="pn">DGFT</div><div className="pd">Import Export Code (IEC)</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
    <a href="https://efilingservices.ecourts.gov.in/" target="_blank" rel="noopener noreferrer" className="portal reveal js-card" style={{ "--d": "200ms" } as React.CSSProperties} data-item data-title="eCourts judiciary case status" data-cat="Government Portal" data-tags="ecourts case status judiciary portal"><div className="plogo">e-C</div><div><div className="pn">eCourts</div><div className="pd">Case status &amp; e-filing</div></div><span className="pgo">Visit<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></span></a>
  </div>
</div></section>
    </>
  );
}
