import React, { useState } from 'react';

export default function LatestNews() {
  const [isExpanded, setIsExpanded] = useState(false);
  const [bookmarks, setBookmarks] = useState<Set<string>>(new Set());

  const toggleBookmark = (id: string) => {
    setBookmarks(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const handleShare = (title: string) => {
    // In a real app this would trigger Web Share API or a modal
  };

  return (
    <>
      <section id="news" className="pad-s"><div className="wrap">
  <div className="shead reveal in"><div className="st"><div className="sicon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="8" y1="13" x2="16" y2="13" /><line x1="8" y1="17" x2="13" y2="17" /></svg></div><div><h2>Latest legal news</h2><div className="sdesc">MCA, SEBI, RBI, GST, Supreme Court, High Courts, Startup India &amp; DPIIT</div></div></div><a href="https://www.livelaw.in/" target="_blank" rel="noopener noreferrer" className="slink">More on LiveLaw<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></a></div>
  <div className="grid g3" id="newsGrid">
    <article className="card reveal in js-card" data-item data-title="MCA extends AOC-4 and MGT-7 filing deadline" data-cat="Legal News" data-tags="mca roc filing compliance annual return"><div className="ctop"><span className="src-pill">MCA</span><span className="cdate">08 Jul 2026</span></div><h3>MCA extends annual filing deadline for AOC-4 and MGT-7</h3><p className="cbody">The Ministry of Corporate Affairs has granted additional time for annual financial statement and return filings for FY 2025-26, citing V3 portal transition load.</p><div className="ctags"><span className="ctag">ROC</span><span className="ctag">Annual Filing</span><span className="ctag">Companies Act</span></div><div className="cfoot"><a className="cread" href="https://www.mca.gov.in/" target="_blank" rel="noopener noreferrer">Read more<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></a><button className={`iconbtn bm push ${bookmarks.has('news-mca-aoc') ? 'saved' : ''}`} onClick={() => toggleBookmark('news-mca-aoc')} aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button><button className="iconbtn share" data-share="MCA extends annual filing deadline" aria-label="Share" onClick={() => handleShare('MCA extends annual filing deadline')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><path d="m8.6 13.5 6.8 4M15.4 6.5l-6.8 4" /></svg></button></div></article>

    <article className="card reveal in js-card" style={{ "--d": "80ms" } as React.CSSProperties} data-item data-title="SEBI tightens disclosure norms for AIFs" data-cat="Legal News" data-tags="sebi aif disclosure investors securities"><div className="ctop"><span className="src-pill blue">SEBI</span><span className="cdate">05 Jul 2026</span></div><h3>SEBI tightens disclosure norms for Alternative Investment Funds</h3><p className="cbody">New circular mandates enhanced periodic disclosures and valuation transparency for AIFs, affecting how startups raising from funds structure their rounds.</p><div className="ctags"><span className="ctag">AIF</span><span className="ctag">Fundraising</span><span className="ctag">Securities</span></div><div className="cfoot"><a className="cread" href="https://www.sebi.gov.in/" target="_blank" rel="noopener noreferrer">Read more<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></a><button className={`iconbtn bm push ${bookmarks.has('news-sebi-aif') ? 'saved' : ''}`} onClick={() => toggleBookmark('news-sebi-aif')} aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button><button className="iconbtn share" data-share="SEBI tightens AIF disclosure norms" aria-label="Share" onClick={() => handleShare('SEBI tightens AIF disclosure norms')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><path d="m8.6 13.5 6.8 4M15.4 6.5l-6.8 4" /></svg></button></div></article>

    <article className="card reveal in js-card" style={{ "--d": "160ms" } as React.CSSProperties} data-item data-title="Supreme Court on arbitration seat and venue" data-cat="Legal News" data-tags="supreme court arbitration seat venue judgment"><div className="ctop"><span className="src-pill red">SUPREME COURT</span><span className="cdate">03 Jul 2026</span></div><h3>Supreme Court clarifies seat vs venue in arbitration agreements</h3><p className="cbody">A three-judge bench settles conflicting precedent on determining the juridical seat of arbitration, with direct impact on commercial contract drafting.</p><div className="ctags"><span className="ctag">Arbitration</span><span className="ctag">Commercial</span><span className="ctag">Contracts</span></div><div className="cfoot"><a className="cread" href="https://www.barandbench.com/" target="_blank" rel="noopener noreferrer">Read more<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></a><button className={`iconbtn bm push ${bookmarks.has('news-sc-arb') ? 'saved' : ''}`} onClick={() => toggleBookmark('news-sc-arb')} aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button><button className="iconbtn share" data-share="SC clarifies seat vs venue in arbitration" aria-label="Share" onClick={() => handleShare('SC clarifies seat vs venue')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><path d="m8.6 13.5 6.8 4M15.4 6.5l-6.8 4" /></svg></button></div></article>

    {isExpanded && (
      <>
        <article className="card reveal in js-card nm" data-item data-title="RBI revises FEMA reporting for FDI" data-cat="Legal News" data-tags="rbi fema fdi foreign investment fcgpr"><div className="ctop"><span className="src-pill ok">RBI</span><span className="cdate">01 Jul 2026</span></div><h3>RBI revises FEMA reporting timelines for foreign investment</h3><p className="cbody">Updated FC-GPR and FC-TRS filing windows tighten reporting for startups receiving FDI, with penalties for late single-master-form submissions.</p><div className="ctags"><span className="ctag">FEMA</span><span className="ctag">FDI</span><span className="ctag">FC-GPR</span></div><div className="cfoot"><a className="cread" href="https://www.rbi.org.in/" target="_blank" rel="noopener noreferrer">Read more<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></a><button className={`iconbtn bm push ${bookmarks.has('news-rbi-fema') ? 'saved' : ''}`} onClick={() => toggleBookmark('news-rbi-fema')} aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button><button className="iconbtn share" data-share="RBI revises FEMA reporting for FDI" aria-label="Share" onClick={() => handleShare('RBI revises FEMA reporting')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><path d="m8.6 13.5 6.8 4M15.4 6.5l-6.8 4" /></svg></button></div></article>

        <article className="card reveal in js-card nm" data-item data-title="GST Council recommends rate rationalisation" data-cat="Legal News" data-tags="gst council rate itc returns tax"><div className="ctop"><span className="src-pill">GST</span><span className="cdate">28 Jun 2026</span></div><h3>GST Council recommends rate rationalisation and ITC changes</h3><p className="cbody">The 54th GST Council meeting proposes slab restructuring and clarifies input tax credit eligibility on several disputed categories relevant to SaaS and services.</p><div className="ctags"><span className="ctag">GST</span><span className="ctag">ITC</span><span className="ctag">Tax</span></div><div className="cfoot"><a className="cread" href="https://www.gst.gov.in/" target="_blank" rel="noopener noreferrer">Read more<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></a><button className={`iconbtn bm push ${bookmarks.has('news-gst-rate') ? 'saved' : ''}`} onClick={() => toggleBookmark('news-gst-rate')} aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button><button className="iconbtn share" data-share="GST Council recommends rate rationalisation" aria-label="Share" onClick={() => handleShare('GST Council recommends rate rationalisation')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><path d="m8.6 13.5 6.8 4M15.4 6.5l-6.8 4" /></svg></button></div></article>

        <article className="card reveal in js-card nm" data-item data-title="DPIIT eases Startup India recognition criteria" data-cat="Legal News" data-tags="dpiit startup india recognition tax exemption 80iac"><div className="ctop"><span className="src-pill ok">DPIIT · STARTUP INDIA</span><span className="cdate">24 Jun 2026</span></div><h3>DPIIT eases Startup India recognition and 80-IAC criteria</h3><p className="cbody">Revised eligibility broadens access to tax exemptions and self-certification benefits under the Startup India scheme for early-stage ventures.</p><div className="ctags"><span className="ctag">Startup India</span><span className="ctag">80-IAC</span><span className="ctag">DPIIT</span></div><div className="cfoot"><a className="cread" href="https://www.startupindia.gov.in/" target="_blank" rel="noopener noreferrer">Read more<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M7 17 17 7M7 7h10v10" /></svg></a><button className={`iconbtn bm push ${bookmarks.has('news-dpiit') ? 'saved' : ''}`} onClick={() => toggleBookmark('news-dpiit')} aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button><button className="iconbtn share" data-share="DPIIT eases Startup India recognition" aria-label="Share" onClick={() => handleShare('DPIIT eases Startup India recognition')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><path d="m8.6 13.5 6.8 4M15.4 6.5l-6.8 4" /></svg></button></div></article>
      </>
    )}
  </div>
  {!isExpanded && (
    <div className="loadmore"><button className="btn btn-ghost" onClick={() => setIsExpanded(true)}>Load more news <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9l6 6 6-6" /></svg></button></div>
  )}
</div></section>
    </>
  );
}
