import React from 'react';

export default function ResearchPapers() {
  return (
    <>
      <section id="research" className="pad-s"><div className="wrap">
  <div className="shead reveal"><div className="st"><div className="sicon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M9 3h6M10 3v5.5L4.5 18a2 2 0 0 0 1.7 3h11.6a2 2 0 0 0 1.7-3L14 8.5V3" /></svg></div><div><h2>Research papers &amp; whitepapers</h2><div className="sdesc">Deeper reading on law, technology, and policy</div></div></div></div>
  <div className="grid g3">
    <article className="card reveal js-card" data-item data-title="LegalTech in India whitepaper research" data-cat="Whitepaper" data-tags="legaltech research whitepaper policy india"><div className="ctop"><span className="src-pill">WHITEPAPER</span><span className="cdate">2026</span></div><h3>The State of LegalTech in India</h3><p className="cbody">Market map, adoption barriers, and where AI is changing legal work first.</p><div className="cfoot"><a className="cread" href="/#contact">Download PDF<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 15V3m0 12l-4-4m4 4l4-4M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" /></svg></a><button className="iconbtn bm push" data-bm="res-legaltech" aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button></div></article>
    <article className="card reveal js-card" style={{ "--d": "80ms" } as React.CSSProperties} data-item data-title="New criminal codes analysis BNS BNSS BSA" data-cat="Research Paper" data-tags="bns bnss bsa criminal law research analysis"><div className="ctop"><span className="src-pill">RESEARCH</span><span className="cdate">2026</span></div><h3>Reading the New Criminal Codes</h3><p className="cbody">A structural analysis of the BNS, BNSS, and BSA and what changes in practice.</p><div className="cfoot"><a className="cread" href="/#contact">Download PDF<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 15V3m0 12l-4-4m4 4l4-4M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" /></svg></a><button className="iconbtn bm push" data-bm="res-codes" aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button></div></article>
    <article className="card reveal js-card" style={{ "--d": "160ms" } as React.CSSProperties} data-item data-title="Data protection DPDP compliance paper" data-cat="Whitepaper" data-tags="dpdp data protection privacy compliance research"><div className="ctop"><span className="src-pill">WHITEPAPER</span><span className="cdate">2026</span></div><h3>DPDP Act: A Startup's Compliance Path</h3><p className="cbody">What the Digital Personal Data Protection Act means for product and data teams.</p><div className="cfoot"><a className="cread" href="/#contact">Download PDF<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 15V3m0 12l-4-4m4 4l4-4M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" /></svg></a><button className="iconbtn bm push" data-bm="res-dpdp" aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button></div></article>
  </div>
</div></section>
    </>
  );
}
