import React from 'react';

export default function Templates() {
  return (
    <>
      <section id="documents" className="pad-s"><div className="wrap">
  <div className="shead reveal"><div className="st"><div className="sicon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z" /><polyline points="14 3 14 9 20 9" /><line x1="8" y1="13" x2="15" y2="13" /><line x1="8" y1="17" x2="13" y2="17" /></svg></div><div><h2>Legal document library</h2><div className="sdesc">Templates, agreements, and forms, drafted for Indian startups</div></div></div><a href="/docengine.html" className="slink">Generate with DocEngine<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M5 12h14M13 6l6 6-6 6" /></svg></a></div>
  <div className="grid g3">
    <article className="card reveal js-card" data-item data-title="Mutual Non-Disclosure Agreement NDA template" data-cat="Template" data-tags="nda confidentiality template download founder"><div className="ctop"><span className="src-pill ok">TEMPLATE</span><span className="cdate">DOCX · PDF</span></div><h3>Mutual Non-Disclosure Agreement</h3><p className="cbody">A balanced two-way NDA for early conversations with vendors, hires, and partners.</p><div className="cfoot"><a className="cread" href="/docengine.html">Get template<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 15V3m0 12l-4-4m4 4l4-4M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" /></svg></a><button className="iconbtn bm push" data-bm="doc-nda" aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button></div></article>
    <article className="card reveal js-card" style={{ "--d": "80ms" } as React.CSSProperties} data-item data-title="Founders Agreement template equity vesting" data-cat="Template" data-tags="founders agreement equity vesting template cofounder"><div className="ctop"><span className="src-pill ok">TEMPLATE</span><span className="cdate">DOCX · PDF</span></div><h3>Founders' Agreement</h3><p className="cbody">Roles, equity split, vesting, and exit terms between co-founders, in plain language.</p><div className="cfoot"><a className="cread" href="/docengine.html">Get template<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 15V3m0 12l-4-4m4 4l4-4M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" /></svg></a><button className="iconbtn bm push" data-bm="doc-founders" aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button></div></article>
    <article className="card reveal js-card" style={{ "--d": "160ms" } as React.CSSProperties} data-item data-title="Employment Agreement offer letter template" data-cat="Template" data-tags="employment agreement offer letter hr template"><div className="ctop"><span className="src-pill ok">TEMPLATE</span><span className="cdate">DOCX · PDF</span></div><h3>Employment Agreement</h3><p className="cbody">A compliant employment contract with IP assignment, confidentiality, and notice clauses.</p><div className="cfoot"><a className="cread" href="/docengine.html">Get template<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 15V3m0 12l-4-4m4 4l4-4M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" /></svg></a><button className="iconbtn bm push" data-bm="doc-emp" aria-label="Bookmark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg></button></div></article>
  </div>
</div></section>
    </>
  );
}
